# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LinhaMestra
                                 A QGIS plugin
 LinhaMestra
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-04-21
        copyright            : (C) 2026 by Iridium
        email                : Iridium@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Iridium'
__date__ = '2026-04-21'
__copyright__ = '(C) 2026 by Iridium'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LinhaMestra class from file LinhaMestra.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .LinhaMestra import LinhaMestraPlugin
    return LinhaMestraPlugin()
