# -*- coding: utf-8 -*-

"""
/***************************************************************************
 LinhaMestra
                                 A QGIS plugin
 LinhaMestra
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-04-21
        copyright            : (C) 2026 by Iridium
        email                : Iridium@gmail.com
 ***************************************************************************/
"""

__author__ = 'Iridium'
__date__ = '2026-04-21'
__copyright__ = '(C) 2026 by Iridium'

import math
from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingException,
                       QgsGeometry,
                       QgsFeature,
                       QgsWkbTypes,
                       QgsFields,
                       QgsField,
                       QgsPointXY)

class LinhaMestraNumeracaoAlgorithm(QgsProcessingAlgorithm):
    """
    Algoritmo para numeração de linhas de soja seguindo critérios de
    azimute e proximidade perpendicular.
    """

    INPUT = 'INPUT'
    OUTPUT = 'OUTPUT'

    def tr(self, string):
        return QCoreApplication.translate('LinhaMestraNumeracaoAlgorithm', string)

    def createInstance(self):
        return LinhaMestraNumeracaoAlgorithm()

    def name(self):
        return 'linhamestra_numeracao'

    def displayName(self):
        return self.tr('Numeração de Linhas de Soja')

    def group(self):
        return self.tr('Linha Mestra')

    def groupId(self):
        return 'linhamestra'

    def initAlgorithm(self, config):
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Camada de Linhas (Soja)'),
                [QgsProcessing.TypeVectorLine]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Linhas Numeradas'),
                QgsProcessing.TypeVectorLine
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        source = self.parameterAsSource(parameters, self.INPUT, context)
        if source is None:
            raise QgsProcessingException(self.invalidSourceError(parameters, self.INPUT))

        # Configurar campos de saída
        fields = source.fields()
        fields.append(QgsField('pass_id', QVariant.Int))
        fields.append(QgsField('seq_num', QVariant.Int))
        fields.append(QgsField('geomet_tp', QVariant.String))

        (sink, dest_id) = self.parameterAsSink(
            parameters, 
            self.OUTPUT, 
            context, 
            fields, 
            source.wkbType(), 
            source.sourceCrs()
        )

        # Parâmetros de negócio definidos no requisito
        DESVIO_ACEITAVEL_TIPO = 5.0
        DESVIO_ACEITAVEL_SEQUENCIA = 2.0
        TOLERANCIA_GPS = 0.5

        features = list(source.getFeatures())
        line_data = []

        # ETAPA 1 - Classificação e Cálculo de Azimute Médio
        for feat in features:
            geom = feat.geometry()
            polyline = geom.asPolyline()
            
            if not polyline:
                continue

            is_straight = True
            avg_az = 0
            
            if len(polyline) == 2:
                is_straight = True
                avg_az = polyline[0].azimuth(polyline[1])
            else:
                # Explode a linha e calcula azimutes de cada segmento
                segment_azs = []
                for i in range(len(polyline) - 1):
                    segment_azs.append(polyline[i].azimuth(polyline[i+1]))
                
                avg_az = sum(segment_azs) / len(segment_azs)
                
                # Verifica se o azimute médio passa do desvio aceitável
                for az in segment_azs:
                    diff = abs(az - avg_az)
                    if diff > 180: diff = 360 - diff
                    if diff > DESVIO_ACEITAVEL_TIPO:
                        is_straight = False
                        break
            
            line_data.append({
                'feat': feat,
                'type': 'RETA' if is_straight else 'CURVA',
                'azimuth': avg_az,
                'centroid': geom.centroid().asPoint(),
                'group': -1,
                'num': 0
            })

        # Agrupamento (Mesma Passada)
        adj = {i: [] for i in range(len(line_data))}
        for i in range(len(line_data)):
            if line_data[i]['type'] != 'RETA': continue
            for j in range(i + 1, len(line_data)):
                if line_data[j]['type'] != 'RETA': continue
                
                # Diferença de azimute
                az_diff = abs(line_data[i]['azimuth'] - line_data[j]['azimuth'])
                if az_diff > 180: az_diff = 360 - az_diff
                
                if az_diff < DESVIO_ACEITAVEL_SEQUENCIA:
                    # Distância perpendicular usando fórmula de projeção
                    p1 = line_data[i]['centroid']
                    p2 = line_data[j]['centroid']
                    rad = math.radians(line_data[i]['azimuth'])
                    
                    v1 = -p1.x() * math.sin(rad) + p1.y() * math.cos(rad)
                    v2 = -p2.x() * math.sin(rad) + p2.y() * math.cos(rad)
                    
                    if abs(v1 - v2) < TOLERANCIA_GPS:
                        adj[i].append(j)
                        adj[j].append(i)

        # ETAPA 2 - Numeração por Grupo
        visited = set()
        group_id_counter = 1
        
        for i in range(len(line_data)):
            if line_data[i]['type'] == 'CURVA':
                # SE LINHA CURVA 1 IMPLEMENTAR PASS
                pass
                continue
                
            if i in visited:
                continue
            
            # Identificar Grupo (Passada) via BFS para fechar componentes
            component = []
            queue = [i]
            visited.add(i)
            while queue:
                u = queue.pop(0)
                component.append(u)
                for v in adj[u]:
                    if v not in visited:
                        visited.add(v)
                        queue.append(v)
            
            # Ordenar linhas dentro do grupo pelo valor de projeção
            group_items = []
            for idx in component:
                d = line_data[idx]
                rad = math.radians(d['azimuth'])
                # valor = -x * sin(azimute) + y * cos(azimute)
                proj_val = -d['centroid'].x() * math.sin(rad) + d['centroid'].y() * math.cos(rad)
                group_items.append((idx, proj_val))
            
            group_items.sort(key=lambda x: x[1])
            
            # Atribuir números sequenciais dentro do grupo
            for seq, (idx, _) in enumerate(group_items, 1):
                line_data[idx]['group'] = group_id_counter
                line_data[idx]['num'] = seq
            
            group_id_counter += 1

        # Salvar feições processadas no sink de saída
        for d in line_data:
            out_feat = QgsFeature(fields)
            out_feat.setGeometry(d['feat'].geometry())
            new_attrs = d['feat'].attributes()
            new_attrs.extend([d['group'], d['num'], d['type']])
            out_feat.setAttributes(new_attrs)
            sink.addFeature(out_feat, QgsFeatureSink.FastInsert)

        return {self.OUTPUT: dest_id}