# -*- coding: utf-8 -*-

"""
/***************************************************************************
 LinhaMestra
                                 A QGIS plugin
 LinhaMestra
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-04-21
        copyright            : (C) 2026 by Iridium
        email                : Iridium@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Iridium'
__date__ = '2026-04-21'
__copyright__ = '(C) 2026 by Iridium'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterNumber,
                       QgsProcessingException,
                       QgsGeometry,
                       QgsFeature,
                       QgsWkbTypes,
                       QgsCoordinateTransform,
                       QgsCoordinateReferenceSystem,
                       QgsPointXY,
                       QgsFields,
                       QgsField)

class LinhaMestraAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    INPUT_2 = 'INPUT_2'
    INTERMEDIATE_LINES_OUTPUT = 'INTERMEDIATE_LINES_OUTPUT'
    PARTICOES = 'PARTICOES'

    def initAlgorithm(self, config):
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Primeira Camada (ou camada com as 2 linhas)'),
                [QgsProcessing.TypeVectorLine]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT_2,
                self.tr('Segunda Camada (Opcional - para 1 feição cada)'),
                [QgsProcessing.TypeVectorLine],
                optional=True
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.PARTICOES,
                self.tr('Número de Partiçôes'),
                type=QgsProcessingParameterNumber.Integer,
                minValue=10,
                maxValue=999999,
                defaultValue=1000
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Linha Mestra'),
                QgsProcessing.TypeVectorLine
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.INTERMEDIATE_LINES_OUTPUT,
                self.tr('Linhas Intermediárias (Conexões)'),
                QgsProcessing.TypeVectorLine
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        source = self.parameterAsSource(parameters, self.INPUT, context)
        source2 = self.parameterAsSource(parameters, self.INPUT_2, context)
        particoes = self.parameterAsInt(parameters, self.PARTICOES, context)

        feicoes_camada1 = list(source.getFeatures())
        linha1 = None
        linha2 = None

        # Validação de Cenários
        if source2 is None:
            # Cenário 1: Duas feições na mesma camada
            if len(feicoes_camada1) != 2:
                raise QgsProcessingException(self.tr('Selecione exatamente 2 feições na camada de entrada.'))
            linha1 = feicoes_camada1[0]
            linha2 = feicoes_camada1[1]
            crs_final = source.sourceCrs()
        else:
            # Cenário 2: Uma feição em cada camada
            feicoes_camada2 = list(source2.getFeatures())
            if len(feicoes_camada1) != 1 or len(feicoes_camada2) != 1:
                raise QgsProcessingException(self.tr('Selecione exatamente 1 feição em cada camada.'))
            
            linha1 = feicoes_camada1[0]
            linha2 = feicoes_camada2[0]
            crs_final = source.sourceCrs()

            # Garantir mesma projeção
            if source.sourceCrs() != source2.sourceCrs():
                feedback.pushInfo(self.tr('Reprojetando segunda camada para a projeção da primeira...'))
                transform = QgsCoordinateTransform(source2.sourceCrs(), source.sourceCrs(), context.transformContext())
                geom2 = linha2.geometry()
                geom2.transform(transform)
                linha2.setGeometry(geom2)

        def orientar_noroeste(geom):
            """Inverte a linha se o final for mais ao Norte/Oeste que o início."""
            polyline = geom.asPolyline()
            if not polyline:
                return geom
            
            inicio = polyline[0]
            fim = polyline[-1]

            # Critério NO: Menor X (Oeste), se empate, maior Y (Norte)
            def score_no(pt):
                return (pt.x(), -pt.y())

            if score_no(fim) < score_no(inicio):
                feedback.pushInfo(self.tr('Invertendo direção da linha para alinhar ao Noroeste.'))
                points = list(polyline)
                points.reverse()
                return QgsGeometry.fromPolylineXY(points)
            return geom

        geom1 = orientar_noroeste(linha1.geometry())
        geom2 = orientar_noroeste(linha2.geometry())

        # Gerar vértices fatiados
        len1 = geom1.length()
        len2 = geom2.length()
        
        # Otimização: Coletamos todos os pontos necessários em um único passo
        dados_particao = []

        for i in range(particoes + 1):
            if feedback.isCanceled():
                break
            
            d1 = (len1 / particoes) * i
            d2 = (len2 / particoes) * i

            g1 = geom1.interpolate(d1)
            g2 = geom2.interpolate(d2)

            if g1.isNull() or g2.isNull():
                continue

            p1 = g1.asPoint()
            p2 = g2.asPoint()
            dist_mae = p1.distance(p2)
            centro = QgsPointXY((p1.x() + p2.x()) / 2, (p1.y() + p2.y()) / 2)
            
            dados_particao.append({
                'p1': p1,
                'p2': p2,
                'centro': centro,
                'dist': dist_mae
            })
            
            feedback.setProgress(int((i / (particoes + 1)) * 50))

        # Definir os campos de saída (ID do segmento)
        fields_mestra = QgsFields()
        fields_mestra.append(QgsField('id_segmento', QVariant.Int))
        fields_mestra.append(QgsField('dist_mae', QVariant.Double))
        
        (sink, dest_id) = self.parameterAsSink(
            parameters, 
            self.OUTPUT,
            context, 
            fields_mestra, 
            QgsWkbTypes.LineString, 
            crs_final # CRS da primeira camada
        )

        # Configurar o sink para as linhas intermediárias
        fields_intermediate = QgsFields()
        fields_intermediate.append(QgsField('id_conexao', QVariant.Int))
        (sink_intermediate, dest_id_intermediate) = self.parameterAsSink(
            parameters,
            self.INTERMEDIATE_LINES_OUTPUT,
            context,
            fields_intermediate,
            QgsWkbTypes.LineString,
            crs_final
        )

        # Criar as feições para cada pedaço (segmento)
        total_pontos = len(dados_particao)
        for i in range(total_pontos):
            if feedback.isCanceled():
                break
            
            item = dados_particao[i]

            # 1. Gerar Segmento da Linha Mestra (conecta o centroide atual ao próximo)
            if i < total_pontos - 1:
                proximo = dados_particao[i+1]
                geom_mestra = QgsGeometry.fromPolylineXY([item['centro'], proximo['centro']])
                feat_mestra = QgsFeature(fields_mestra)
                feat_mestra.setGeometry(geom_mestra)
                feat_mestra.setAttribute('id_segmento', i + 1)
                feat_mestra.setAttribute('dist_mae', item['dist'])
                sink.addFeature(feat_mestra, QgsFeatureSink.FastInsert)

            # 2. Gerar Linha de Conexão (Travessa transversal entre as linhas originais)
            geom_conn = QgsGeometry.fromPolylineXY([item['p1'], item['p2']])
            feat_conn = QgsFeature(fields_intermediate)
            feat_conn.setGeometry(geom_conn)
            feat_conn.setAttribute('id_conexao', i + 1)
            sink_intermediate.addFeature(feat_conn, QgsFeatureSink.FastInsert)
            
            feedback.setProgress(50 + int((i / total_pontos) * 50))

        return {self.OUTPUT: dest_id, self.INTERMEDIATE_LINES_OUTPUT: dest_id_intermediate}

    def name(self):
        return 'linhamestra_gerador'

    def displayName(self):
        return self.tr('Gerador de Linha Mestra')

    def group(self):
        return self.tr('Linha Mestra')

    def groupId(self):
        return 'linhamestra'

    def tr(self, string):
        return QCoreApplication.translate('LinhaMestraAlgorithm', string)

    def createInstance(self):
        return LinhaMestraAlgorithm()
