# -*- coding: utf-8 -*-

"""
/***************************************************************************
 LinhaMestra
                                 A QGIS plugin
 LinhaMestra
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-04-21
        copyright            : (C) 2026 by Iridium
        email                : Iridium@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Iridium'
__date__ = '2026-04-21'
__copyright__ = '(C) 2026 by Iridium'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterEnum,
                       QgsProcessingException,
                       QgsGeometry,
                       QgsFeature,
                       QgsWkbTypes,
                       QgsFields,
                       QgsField)
from .vector_utils import VectorUtils
from .connection_judge import ConnectionJudge

class LinhaMestraAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    INPUT_2 = 'INPUT_2'
    INTERMEDIATE_LINES_OUTPUT = 'INTERMEDIATE_LINES_OUTPUT'
    PERPENDICULAR_OUTPUT = 'PERPENDICULAR_OUTPUT'
    NEAREST_OUTPUT = 'NEAREST_OUTPUT'
    CRITERIO_PROXIMIDADE = 'CRITERIO_PROXIMIDADE'
    PARTICOES = 'PARTICOES'

    def initAlgorithm(self, config):
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Primeira Camada (ou camada com as 2 linhas)'),
                [QgsProcessing.TypeVectorLine]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT_2,
                self.tr('Segunda Camada (Opcional - para 1 feição cada)'),
                [QgsProcessing.TypeVectorLine],
                optional=True
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.PARTICOES,
                self.tr('Número de Partiçôes'),
                type=QgsProcessingParameterNumber.Integer,
                minValue=10,
                maxValue=999999,
                defaultValue=1000
            )
        )

        self.addParameter(
            QgsProcessingParameterEnum(
                self.CRITERIO_PROXIMIDADE,
                self.tr('Critério de Proximidade (Escolha da Base)'),
                options=['Menor Tamanho', 'Maior Tamanho', 'Menor Ângulo', 'Maior Ângulo', 'Qualquer uma'],
                defaultValue=4
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Linha Mestra'),
                QgsProcessing.TypeVectorLine
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.INTERMEDIATE_LINES_OUTPUT,
                self.tr('Linhas Intermediárias (Conexões)'),
                QgsProcessing.TypeVectorLine
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.PERPENDICULAR_OUTPUT,
                self.tr('Linhas Perpendiculares (Bissetriz)'),
                QgsProcessing.TypeVectorLine
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.NEAREST_OUTPUT,
                self.tr('Menor Distância (Proximidade)'),
                QgsProcessing.TypeVectorLine
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        source = self.parameterAsSource(parameters, self.INPUT, context)
        source2 = self.parameterAsSource(parameters, self.INPUT_2, context)
        particoes = self.parameterAsInt(parameters, self.PARTICOES, context)
        criterio = self.parameterAsInt(parameters, self.CRITERIO_PROXIMIDADE, context)

        # 1. Extração e Validação (Delegado para VectorUtils)
        linha1, linha2, crs_final = VectorUtils.extract_two_features(source, source2, context)
        if linha1 is None:
            raise QgsProcessingException(self.tr('Erro de Seleção: Escolha 2 feições na mesma camada ou 1 em cada camada.'))

        # 2. Processamento Geométrico Pesado (Delegado para VectorUtils)
        mestra_results, conexao_results, perp_results = VectorUtils.generate_linhamestra_elements(
            linha1.geometry(), linha2.geometry(), particoes, feedback
        )

        # 2.1. Julgamento das Conexões de Menor Distância (Novo Juiz)
        near_results = ConnectionJudge.solve_nearest_with_criteria(
            linha1.geometry(), linha2.geometry(), criterio)

        # Definir os campos de saída (ID do segmento)
        fields_mestra = QgsFields()
        fields_mestra.append(QgsField('id_segmento', QVariant.Int))
        fields_mestra.append(QgsField('dist_mae', QVariant.Double))
        
        (sink, dest_id) = self.parameterAsSink(
            parameters, 
            self.OUTPUT,
            context, 
            fields_mestra, 
            QgsWkbTypes.LineString, 
            crs_final # CRS da primeira camada
        )

        # Configurar o sink para as linhas intermediárias
        fields_intermediate = QgsFields()
        fields_intermediate.append(QgsField('id_conexao', QVariant.Int))
        (sink_intermediate, dest_id_intermediate) = self.parameterAsSink(
            parameters,
            self.INTERMEDIATE_LINES_OUTPUT,
            context,
            fields_intermediate,
            QgsWkbTypes.LineString,
            crs_final
        )

        # Configurar o sink para as linhas perpendiculares
        fields_perp = QgsFields()
        fields_perp.append(QgsField('id_perp', QVariant.Int))
        (sink_perp, dest_id_perp) = self.parameterAsSink(
            parameters, self.PERPENDICULAR_OUTPUT, context, fields_perp, QgsWkbTypes.LineString, crs_final
        )

        # Sinks para as novas camadas de proximidade
        fields_near = QgsFields()
        fields_near.append(QgsField('id_ponto', QVariant.Int))
        
        (sink_near, dest_id_near) = self.parameterAsSink(
            parameters, self.NEAREST_OUTPUT, context, fields_near, QgsWkbTypes.LineString, crs_final
        )

        # 3. Escrita dos Resultados (Orquestração pura)
        feedback.pushInfo(self.tr('Escrevendo feições na camada de saída...'))

        def write_results(results, sink, fields):
            for res in results:
                if feedback.isCanceled(): break
                feat = VectorUtils.create_feature(res['geom'], fields, [res['id']])
                sink.addFeature(feat, QgsFeatureSink.FastInsert)

        # Mestra precisa de um campo extra (dist_mae), então fazemos manual
        for i, res in enumerate(mestra_results):
            if feedback.isCanceled(): break
            feat = VectorUtils.create_feature(res['geom'], fields_mestra, [res['id'], res['dist']])
            sink.addFeature(feat, QgsFeatureSink.FastInsert)

        write_results(conexao_results, sink_intermediate, fields_intermediate)
        write_results(perp_results, sink_perp, fields_perp)
        write_results(near_results, sink_near, fields_near)

        return {
            self.OUTPUT: dest_id, 
            self.INTERMEDIATE_LINES_OUTPUT: dest_id_intermediate,
            self.PERPENDICULAR_OUTPUT: dest_id_perp,
            self.NEAREST_OUTPUT: dest_id_near
        }

    def name(self):
        return 'linhamestra_gerador'

    def displayName(self):
        return self.tr('Gerador de Linha Mestra')

    def group(self):
        return self.tr('Linha Mestra')

    def groupId(self):
        return 'linhamestra'

    def tr(self, string):
        return QCoreApplication.translate('LinhaMestraAlgorithm', string)

    def createInstance(self):
        return LinhaMestraAlgorithm()
