# -*- coding: utf-8 -*-

"""
/***************************************************************************
 LinhaMestra
                                 A QGIS plugin
 LinhaMestra
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-04-21
        copyright            : (C) 2026 by Iridium
        email                : Iridium@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Iridium'
__date__ = '2026-04-21'
__copyright__ = '(C) 2026 by Iridium'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterDefinition,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterBoolean,
                       QgsProcessingException,
                       QgsGeometry,
                       QgsFeature,
                       QgsWkbTypes,
                       QgsFields,
                       QgsField)
from ..core.vector_utils import VectorUtils
from ..core.connection_judge import ConnectionJudge

class LinhaMestraAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    INPUT_2 = 'INPUT_2'
    CONEXAO_OUTPUT = 'CONEXAO_OUTPUT'
    CRITERIO_PROXIMIDADE = 'CRITERIO_PROXIMIDADE'
    ESTILO_CONEXAO = 'ESTILO_CONEXAO'
    ESTILO_LINHA_MESTRA = 'ESTILO_LINHA_MESTRA'
    PARTICOES = 'PARTICOES'
    REDUCAO_FILTRO = 'REDUCAO_FILTRO'
    RESOLVER_ORFAOS_PONTAS = 'RESOLVER_ORFAOS_PONTAS'
    ESPACAMENTO = 'ESPACAMENTO'

    def initAlgorithm(self, config):
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Primeira Camada (ou camada com as 2 linhas)'),
                [QgsProcessing.TypeVectorLine]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT_2,
                self.tr('Segunda Camada (Opcional - para 1 feição cada)'),
                [QgsProcessing.TypeVectorLine],
                optional=True
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.PARTICOES,
                self.tr('Número de Partiçôes'),
                type=QgsProcessingParameterNumber.Integer,
                minValue=10,
                maxValue=999999,
                defaultValue=1000
            )
        )

        self.addParameter(
            QgsProcessingParameterEnum(
                self.ESTILO_CONEXAO,
                self.tr('Estilo de Conexão'),
                options=['Proximidade', 'Perpendicular', 'Conexão Direta (Ponto a Ponto)', 'Espaçamento Fixo (1:1)'],
                defaultValue=0
            )
        )

        self.addParameter(
            QgsProcessingParameterEnum(
                self.ESTILO_LINHA_MESTRA,
                self.tr('Estilo da Linha Mestra'),
                options=['Interpolação (Ponto a Ponto)', 'Proximidade (Média Espacial)', 'Espaçamento Fixo (1:1)'],
                defaultValue=1
            )
        )

        self.addParameter(
            QgsProcessingParameterEnum(
                self.CRITERIO_PROXIMIDADE,
                self.tr('Critério de Proximidade (Escolha da Base)'),
                options=['Ponto na Ponta -> Meio (Sincronismo)', 'Menor Tamanho', 'Maior Tamanho', 'Menor Ângulo', 'Maior Ângulo'],
                defaultValue=0
            )
        )

        self.addParameter(
            QgsProcessingParameterBoolean(
                self.RESOLVER_ORFAOS_PONTAS,
                self.tr('Resolver órfãos das pontas no método de Proximidade'),
                defaultValue=False
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.ESPACAMENTO,
                self.tr('Espaçamento Fixo (Metros)'),
                type=QgsProcessingParameterNumber.Double,
                minValue=0.1,
                defaultValue=1.0
            )
        )

        param_reducao = QgsProcessingParameterNumber(
            self.REDUCAO_FILTRO,
            self.tr('Redução para Filtro de Cruzamento (metros)'),
            type=QgsProcessingParameterNumber.Double,
            minValue=0.0,
            maxValue=1.0,
            defaultValue=1
        )
        param_reducao.setFlags(QgsProcessingParameterDefinition.FlagAdvanced)
        self.addParameter(param_reducao)

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Linha Mestra'),
                QgsProcessing.TypeVectorLine
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.CONEXAO_OUTPUT,
                self.tr('Conexões'),
                QgsProcessing.TypeVectorLine
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        source = self.parameterAsSource(parameters, self.INPUT, context)
        source2 = self.parameterAsSource(parameters, self.INPUT_2, context)
        particoes = self.parameterAsInt(parameters, self.PARTICOES, context)
        criterio = self.parameterAsInt(parameters, self.CRITERIO_PROXIMIDADE, context)
        estilo = self.parameterAsInt(parameters, self.ESTILO_CONEXAO, context)
        estilo_mestra = self.parameterAsInt(parameters, self.ESTILO_LINHA_MESTRA, context)
        resolve_pontas = self.parameterAsBool(parameters, self.RESOLVER_ORFAOS_PONTAS, context)
        reducao = self.parameterAsDouble(parameters, self.REDUCAO_FILTRO, context)
        espacamento = self.parameterAsDouble(parameters, self.ESPACAMENTO, context)

        # 1. Extração e Validação (Delegado para VectorUtils)
        linha1, linha2, crs_final = VectorUtils.extract_two_features(source, source2, context)
        if linha1 is None:
            raise QgsProcessingException(self.tr('Erro de Seleção: Escolha 2 feições na mesma camada ou 1 em cada camada.'))

        # 2. Lógica de Pipeline Otimizada
        g1, g2 = VectorUtils.align_line_pair(linha1.geometry(), linha2.geometry())

        # Determinar o número alvo de segmentos (partições) baseado no maior valor
        v_count1 = sum(1 for _ in g1.vertices())
        v_count2 = sum(1 for _ in g2.vertices())
        target_n = max(particoes, v_count1 - 1, v_count2 - 1)
        
        # Determinar quais dados precisamos calcular para evitar duplicidade
        needs_near = (estilo_mestra == 1 or estilo == 0)
        needs_interp = (estilo_mestra == 0 or estilo == 2 or estilo == 1) # Perpendicular também precisa de interp
        needs_1to1 = (estilo_mestra == 2 or estilo == 3)
        
        near_conns = []
        fixed_conns = []
        interp_conns = []
        perp_results = []

        # A. Processamento por Proximidade
        if needs_near:
            feedback.pushInfo(self.tr('Calculando conexões por Proximidade...'))
            near_conns = ConnectionJudge.solve_nearest_with_criteria(g1, g2, criterio, target_n, resolve_pontas)
            near_conns = VectorUtils.filter_connections(near_conns, g1, g2, crs_final, reducao)

        # B. Processamento por Interpolação (Ponto a Ponto)
        if needs_interp:
            feedback.pushInfo(self.tr('Calculando conexões por Interpolação...'))
            m_results, c_results, p_results = VectorUtils.generate_linhamestra_elements(g1, g2, target_n, feedback)
            interp_conns = VectorUtils.filter_connections(c_results, g1, g2, crs_final, reducao)
            perp_results = p_results # As perpendiculares são geradas no fluxo de interpolação
            interp_mestra_results = m_results

        # C. Processamento 1:1
        if needs_1to1:
            feedback.pushInfo(self.tr('Calculando conexões por Espaçamento Fixo (1:1)...'))
            g_pai, g_mae = VectorUtils.align_by_endpoint_logic(linha1.geometry(), linha2.geometry())
            fixed_conns = VectorUtils.generate_1to1_connections(g_pai, g_mae, espacamento)
            fixed_conns = VectorUtils.filter_connections(fixed_conns, g_pai, g_mae, crs_final, reducao)

        # 3. Definição da Linha Mestra Final
        if estilo_mestra == 1:
            mestra_final = VectorUtils.generate_mestra_from_connections(near_conns)
        elif estilo_mestra == 2:
            mestra_final = VectorUtils.generate_mestra_from_connections(fixed_conns)
        else:
            mestra_final = VectorUtils.generate_mestra_from_connections(interp_conns)

        # 4. Seleção do estilo de conexão para saída
        if estilo == 0:
            conexao_final_results = near_conns
        elif estilo == 1: # Perpendicular
            conexao_final_results = perp_results
        elif estilo == 3: # 1:1
            conexao_final_results = fixed_conns
        else: # Conexão Direta (Ponto a Ponto)
            conexao_final_results = interp_conns

        # Definir os campos de saída (ID do segmento)
        fields_mestra = QgsFields()
        fields_mestra.append(QgsField('id_segmento', QVariant.Int))
        fields_mestra.append(QgsField('dist_mae', QVariant.Double))
        
        (sink, dest_id) = self.parameterAsSink(
            parameters, 
            self.OUTPUT,
            context, 
            fields_mestra, 
            QgsWkbTypes.LineString, 
            crs_final # CRS da primeira camada
        )

        # Configurar o sink para as conexões (Unificado)
        fields_conexao = QgsFields()
        fields_conexao.append(QgsField('id_conexao', QVariant.Int))
        fields_conexao.append(QgsField('id_pai', QVariant.Double))
        fields_conexao.append(QgsField('id_mae', QVariant.Double))
        fields_conexao.append(QgsField('id_origem', QVariant.Double))
        (sink_conexao, dest_id_conexao) = self.parameterAsSink(
            parameters,
            self.CONEXAO_OUTPUT,
            context,
            fields_conexao,
            QgsWkbTypes.LineString,
            crs_final
        )

        # 3. Escrita dos Resultados (Orquestração pura)
        feedback.pushInfo(self.tr('Escrevendo feições na camada de saída...'))

        def write_results(results, sink, fields):
            for res in results:
                if feedback.isCanceled(): break
                attrs = [
                    res.get('id', 0),
                    res.get('id_pai', 0),
                    res.get('id_mae', 0),
                    res.get('id_origem', 0)
                ]
                feat = VectorUtils.create_feature(res['geom'], fields, attrs)
                sink.addFeature(feat, QgsFeatureSink.FastInsert)

        # Mestra precisa de um campo extra (dist_mae), então fazemos manual
        for i, res in enumerate(mestra_final):
            if feedback.isCanceled(): break
            feat = VectorUtils.create_feature(res['geom'], fields_mestra, [res['id'], res['dist']])
            sink.addFeature(feat, QgsFeatureSink.FastInsert)

        write_results(conexao_final_results, sink_conexao, fields_conexao)

        return {
            self.OUTPUT: dest_id, 
            self.CONEXAO_OUTPUT: dest_id_conexao
        }

    def name(self):
        return 'linhamestra_gerador'

    def displayName(self):
        return self.tr('Gerador de Linha Mestra')

    def group(self):
        return self.tr('Linha Mestra')

    def groupId(self):
        return 'linhamestra'

    def shortHelpString(self):
        return self.tr(
            "════════════════════════════════════════════\n"
            "      GERADOR DE LINHA MESTRA\n"
            "════════════════════════════════════════════\n"
            "\n"
            "▬▬▬ O QUE ESTA FERRAMENTA FAZ ▬▬▬\n"
            "\n"
            "Dadas DUAS linhas no mapa (ex.: margens de\n"
            "uma estrada, bordas de uma calçada, limites\n"
            "laterais de um terreno), esta ferramenta\n"
            "gera automaticamente:\n"
            "\n"
            "  ✅ Linha Mestra — uma linha central entre\n"
            "     as duas bordas (o 'meio do caminho')\n"
            "\n"
            "  ✅ Conexões — linhas transversais ligando\n"
            "     uma borda à outra (como 'travessas')\n"
            "\n"
            "▬▬▬ COMO FORNECER AS LINHAS ▬▬▬\n"
            "\n"
            "Você pode fornecer as 2 linhas de 2 formas:\n"
            "\n"
            "  1) Duas camadas separadas:\n"
            "     1ª camada = linha 1\n"
            "     2ª camada = linha 2\n"
            "     (cada camada com 1 feição)\n"
            "\n"
            "  2) Uma única camada:\n"
            "     1ª camada = linha 1 + linha 2\n"
            "     2ª camada = deixe vazio\n"
            "     (a camada deve ter 2 feições)\n"
            "\n"
            "▬▬▬ PARÂMETROS DETALHADOS ▬▬▬\n"
            "\n"
            "▶ Primeira Camada (OBRIGATÓRIO):\n"
            "  Camada vetorial de linhas contendo a\n"
            "  primeira feição de entrada.\n"
            "\n"
            "▶ Segunda Camada (OPCIONAL):\n"
            "  Segunda camada com a outra feição.\n"
            "  Se omitida, a primeira camada deve\n"
            "  conter exatamente 2 feições.\n"
            "\n"
            "▶ Número de Partições (10 a 999.999):\n"
            "  Padrão: 1000\n"
            "  Define em quantos segmentos as linhas\n"
            "  serão divididas para o cálculo.\n"
            "  • Maior valor = mais preciso\n"
            "  • Menor valor = mais rápido\n"
            "  O valor efetivo usado é:\n"
            "    max(partições, vértices_linha1 - 1,\n"
            "        vértices_linha2 - 1)\n"
            "  Isso garante que cada vértico original\n"
            "  seja considerado no resultado.\n"
            "\n"
            "▶ Estilo de Conexão (como ligar as\n"
            "  duas linhas entre si):\n"
            "\n"
            "  (0) Proximidade:\n"
            "      Conecta cada ponto de uma linha\n"
            "      ao ponto mais próximo da outra.\n"
            "      Usa o Critério de Proximidade\n"
            "      para decidir o emparelhamento.\n"
            "\n"
            "  (1) Perpendicular:\n"
            "      Gera conexões em ângulo reto\n"
            "      (90°) em relação à linha mestra.\n"
            "      Ideal para linhas aproximadamente\n"
            "      paralelas.\n"
            "\n"
            "  (2) Conexão Direta (Ponto a Ponto):\n"
            "      Interpola pontos ao longo de cada\n"
            "      linha e liga índice i → índice i\n"
            "      sequencialmente.\n"
            "\n"
            "  (3) Espaçamento Fixo (1:1):\n"
            "      Gera conexões em intervalos\n"
            "      regulares de X metros ao longo\n"
            "      das linhas. Use com o parâmetro\n"
            "      'Espaçamento Fixo'.\n"
            "\n"
            "▶ Estilo da Linha Mestra (como calcular\n"
            "  a linha central):\n"
            "\n"
            "  (0) Interpolação (Ponto a Ponto):\n"
            "      Interpola pontos igualmente\n"
            "      espaçados em cada linha e calcula\n"
            "      o ponto médio de cada par (i,i).\n"
            "      A linha mestra é a união desses\n"
            "      pontos médios.\n"
            "\n"
            "  (1) Proximidade (Média Espacial):\n"
            "      Usa os pares encontrados pelo\n"
            "      algoritmo de Proximidade e calcula\n"
            "      o ponto médio de cada par.\n"
            "      Padrão.\n"
            "\n"
            "  (2) Espaçamento Fixo (1:1):\n"
            "      Usa as conexões geradas com\n"
            "      intervalo regular e calcula\n"
            "      os pontos médios.\n"
            "\n"
            "▶ Critério de Proximidade (escolha da\n"
            "  base para emparelhamento):\n"
            "\n"
            "  (0) Ponta→Meio (Sincronismo):\n"
            "      Emparelha partindo das\n"
            "      extremidades em direção ao centro.\n"
            "      Sincroniza os índices das duas\n"
            "      linhas.\n"
            "  (1) Menor Tamanho:\n"
            "      Usa a linha mais curta como\n"
            "      base para definir os pares.\n"
            "  (2) Maior Tamanho:\n"
            "      Usa a linha mais longa como\n"
            "      base.\n"
            "  (3) Menor Ângulo:\n"
            "      Prioriza pares com menor\n"
            "      diferença angular entre os\n"
            "      segmentos.\n"
            "  (4) Maior Ângulo:\n"
            "      Prioriza pares com maior\n"
            "      diferença angular.\n"
            "\n"
            "▶ Resolver órfãos das pontas (BOOL):\n"
            "  Padrão: desligado\n"
            "  Quando ativo, tenta conectar pontos\n"
            "  que ficaram sem par nas extremidades\n"
            "  durante o método de Proximidade.\n"
            "  Evita que as pontas das linhas\n"
            "  fiquem 'soltas' sem conexão.\n"
            "\n"
            "▶ Espaçamento Fixo (metros):\n"
            "  Padrão: 1.0 m  |  Mínimo: 0.1 m\n"
            "  Distância entre cada conexão quando\n"
            "  o estilo 'Espaçamento Fixo (1:1)'\n"
            "  é selecionado.\n"
            "\n"
            "▶ Redução para Filtro de Cruzamento:\n"
            "  ⚠️  Avançado\n"
            "  Padrão: 1.0  |  Faixa: 0.0 a 1.0\n"
            "  Fator de redução para filtrar\n"
            "  conexões que se cruzam ou formam\n"
            "  ângulos muito fechados.\n"
            "  • 1.0 = sem filtragem\n"
            "  • 0.5 = elimina metade\n"
            "  • 0.0 = máxima filtragem\n"
            "\n"
            "▬▬▬ ENTENDENDO O PIPELINE TÉCNICO ▬▬▬\n"
            "\n"
            "O algoritmo executa ATÉ 3 pipelines\n"
            "distintos, ativados conforme a\n"
            "combinação de estilos escolhida:\n"
            "\n"
            "PIPELINE A — Proximidade:\n"
            "  ▶ ConnectionJudge.solve_nearest_\n"
            "    with_criteria(g1, g2, criterio,\n"
            "    target_n, resolve_pontas)\n"
            "  ▶ VectorUtils.filter_connections()\n"
            "\n"
            "  Este pipeline emparelha os pontos\n"
            "  das duas linhas usando critérios\n"
            "  espaciais (distância, tamanho,\n"
            "  ângulo). O resultado é uma lista\n"
            "  de conexões onde cada ponto de uma\n"
            "  linha foi casado com o ponto mais\n"
            "  'adequado' da outra segundo o\n"
            "  critério selecionado.\n"
            "\n"
            "PIPELINE B — Interpolação:\n"
            "  ▶ VectorUtils.generate_linhamestra_\n"
            "    elements(g1, g2, target_n)\n"
            "  ▶ VectorUtils.filter_connections()\n"
            "\n"
            "  Este pipeline:\n"
            "  1) Amostra target_n pontos igual-\n"
            "     mente espaçados em cada linha\n"
            "  2) Gera a linha mestra interpolada\n"
            "     (pontos médios par a par)\n"
            "  3) Gera conexões diretas\n"
            "  4) Gera conexões perpendiculares\n"
            "  Tudo em uma única passada.\n"
            "\n"
            "PIPELINE C — Espaçamento Fixo (1:1):\n"
            "  ▶ VectorUtils.align_by_endpoint_\n"
            "    logic(g1, g2)\n"
            "  ▶ VectorUtils.generate_1to1_\n"
            "    connections(g_pai, g_mae,\n"
            "    espacamento)\n"
            "  ▶ VectorUtils.filter_connections()\n"
            "\n"
            "  Este pipeline:\n"
            "  1) Re-alinha as geometrias pelas\n"
            "     extremidades\n"
            "  2) Percorre as linhas a cada\n"
            "     X metros (espaçamento)\n"
            "  3) Gera uma conexão em cada\n"
            "     intervalo\n"
            "\n"
            "▶ COMO OS PIPELINES SÃO ATIVADOS:\n"
            "\n"
            "  O algoritmo avalia 3 flags:\n"
            "    needs_near   = (estilo_mestra==1\n"
            "                    OR estilo==0)\n"
            "    needs_interp = (estilo_mestra==0\n"
            "                    OR estilo==2 OR\n"
            "                    estilo==1)\n"
            "    needs_1to1   = (estilo_mestra==2\n"
            "                    OR estilo==3)\n"
            "\n"
            "  Combinações comuns:\n"
            "  • Proximidade + Mestra=Prox:\n"
            "      só pipeline A\n"
            "  • Perpendicular + Mestra=Interp:\n"
            "      só pipeline B\n"
            "  • Proximidade + Mestra=Interp:\n"
            "      pipelines A + B\n"
            "  • Espaç.Fixo + Mestra=1:1:\n"
            "      só pipeline C\n"
            "  • Proximidade + Mestra=1:1:\n"
            "      pipelines A + C\n"
            "\n"
            "▶ GERAÇÃO DA LINHA MESTRA:\n"
            "\n"
            "  Após os pipelines, a linha mestra\n"
            "  é gerada por:\n"
            "    VectorUtils.generate_mestra_from_\n"
            "    connections(dados)\n"
            "\n"
            "  A origem dos dados varia:\n"
            "  • estilo_mestra=0 (Interpolação):\n"
            "      usa interp_conns\n"
            "  • estilo_mestra=1 (Proximidade):\n"
            "      usa near_conns\n"
            "  • estilo_mestra=2 (1:1):\n"
            "      usa fixed_conns\n"
            "\n"
            "  Para cada par conectado, calcula\n"
            "  o ponto médio e constrói uma\n"
            "  LineString contínua.\n"
            "\n"
            "▶ SELEÇÃO DAS CONEXÕES DE SAÍDA:\n"
            "\n"
            "  • estilo=0 (Proximidade):\n"
            "      usa near_conns\n"
            "  • estilo=1 (Perpendicular):\n"
            "      usa perp_results\n"
            "  • estilo=2 (Conexão Direta):\n"
            "      usa interp_conns\n"
            "  • estilo=3 (Espaçamento Fixo):\n"
            "      usa fixed_conns\n"
            "\n"
            "▬▬▬ RESULTADOS (CAMADAS DE SAÍDA) ▬▬▬\n"
            "\n"
            "📌 Linha Mestra:\n"
            "   Tipo: LineString\n"
            "   Campos:\n"
            "   • id_segmento (Inteiro)\n"
            "     — identificador do segmento\n"
            "   • dist_mae (Decimal)\n"
            "     — distância acumulada até a\n"
            "       linha de referência (mãe)\n"
            "\n"
            "📌 Conexões:\n"
            "   Tipo: LineString\n"
            "   Campos:\n"
            "   • id_conexao (Inteiro)\n"
            "     — identificador da conexão\n"
            "   • id_pai (Decimal)\n"
            "     — índice do ponto na linha pai\n"
            "   • id_mae (Decimal)\n"
            "     — índice do ponto na linha mãe\n"
            "   • id_origem (Decimal)\n"
            "     — índice de origem\n"
            "\n"
            "▬▬▬ RESUMO PARA O USUÁRIO ▬▬▬\n"
            "\n"
            "\"Dê duas linhas para o computador,\n"
            "e ele descobre qual é a linha do\n"
            "meio entre elas, além de criar\n"
            "várias linhas de ligação entre as\n"
            "duas — tudo de forma automática e\n"
            "com vários estilos diferentes para\n"
            "escolher.\""
        )

    def tr(self, string):
        return QCoreApplication.translate('LinhaMestraAlgorithm', string)

    def createInstance(self):
        return LinhaMestraAlgorithm()
