# -*- coding: utf-8 -*-

"""
/***************************************************************************
 LinhaMestra
                                 A QGIS plugin
 LinhaMestra
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-04-21
        copyright            : (C) 2026 by Iridium
        email                : Iridium@gmail.com
 ***************************************************************************/
"""

__author__ = 'Iridium'
__date__ = '2026-04-21'
__copyright__ = '(C) 2026 by Iridium'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingException,
                       QgsProcessingParameterNumber,
                       QgsGeometry,
                       QgsFeature,
                       QgsWkbTypes,
                       QgsFields,
                       QgsField,
                       QgsPointXY,
                       QgsDistanceArea)
from ..core.vector_utils import VectorUtils

class LinhaMestraNumeracaoAlgorithm(QgsProcessingAlgorithm):

    INPUT = 'INPUT'
    OUTPUT = 'OUTPUT'
    
    # Constantes solicitadas
    DESVIO_TIPO = 'DESVIO_ACEITAVEL_TIPO'
    DESVIO_SEQ = 'DESVIO_ACEITAVEL_SEQUENCIA'
    TOL_GPS = 'TOLERANCIA_GPS'

    def tr(self, string):
        return QCoreApplication.translate('LinhaMestraNumeracaoAlgorithm', string)

    def createInstance(self):
        return LinhaMestraNumeracaoAlgorithm()

    def name(self):
        return 'linhamestra_numeracao'

    def displayName(self):
        return self.tr('Numeração de Linhas de Soja')

    def group(self):
        return self.tr('Linha Mestra')

    def groupId(self):
        return 'linhamestra'

    def initAlgorithm(self, config):
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Camada de Linhas (Soja)'),
                [QgsProcessing.TypeVectorLine]
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.DESVIO_TIPO,
                self.tr('Desvio Aceitável Tipo (Graus)'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=5.0
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.DESVIO_SEQ,
                self.tr('Desvio Aceitável Sequência (Graus)'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=2.0
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.TOL_GPS,
                self.tr('Tolerância GPS (Metros)'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=0.5
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Linhas Numeradas'),
                QgsProcessing.TypeVectorLine
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        source = self.parameterAsSource(parameters, self.INPUT, context)
        if source is None:
            raise QgsProcessingException(self.invalidSourceError(parameters, self.INPUT))

        desvio_tipo = self.parameterAsDouble(parameters, self.DESVIO_TIPO, context)
        desvio_seq = self.parameterAsDouble(parameters, self.DESVIO_SEQ, context)
        tol_gps = self.parameterAsDouble(parameters, self.TOL_GPS, context)

        # Configurar campos de saída
        fields = source.fields()
        fields.append(QgsField('grupo_id', QVariant.Int))
        fields.append(QgsField('seq_num', QVariant.Int))
        fields.append(QgsField('geomet_tp', QVariant.String))
        fields.append(QgsField('azimuth', QVariant.Double))

        (sink, dest_id) = self.parameterAsSink(
            parameters, 
            self.OUTPUT, 
            context, 
            fields, 
            source.wkbType(), 
            source.sourceCrs()
        )

        features = list(source.getFeatures())
        line_data = []

        # ETAPA 1 - Classificação e Cálculo de Azimute Médio
        for feat in features:
            geom = feat.geometry()
            
            # Processamento delegado para VectorUtils (Suporta Line e MultiLine)
            is_straight, avg_az, max_dev = VectorUtils.analyze_straightness(geom, desvio_tipo)
            tipo_str = "RETA" if is_straight else "CURVA"
            feedback.pushInfo(f"Linha {feat.id()}: {tipo_str} (Média Az: {avg_az:.2f}°, Desvio Máx: {max_dev:.2f}°)")
            
            # Armazenamos a geometria original para o centroide
            centroid_pt = geom.centroid().asPoint()
            if centroid_pt.isEmpty(): # Fallback para linhas sem centroide válido
                nodes = list(geom.vertices())
                centroid_pt = QgsPointXY(nodes[0].x(), nodes[0].y()) if nodes else QgsPointXY(0,0)

            line_data.append({
                'feat': feat,
                'fid': feat.id(),
                'type': tipo_str,
                'azimuth': avg_az,
                'centroid': centroid_pt,
                'grupo_id': 0,
                'seq_num': 0
            })

        # ETAPA 1 — JUNTAR SEGMENTOS DA MESMA PASSADA
        adj = {i: [] for i in range(len(line_data))}
        for i in range(len(line_data)):
            if line_data[i]['type'] != 'RETA': continue
            for j in range(i + 1, len(line_data)):
                if line_data[j]['type'] != 'RETA': continue
                
                az_diff = abs(line_data[i]['azimuth'] - line_data[j]['azimuth'])
                if az_diff > 180: az_diff = 360 - az_diff
                
                if az_diff < desvio_seq:
                    p1 = line_data[i]['centroid']
                    p2 = line_data[j]['centroid']
                    v1 = VectorUtils.get_projection_value(p1, line_data[i]['azimuth'])
                    v2 = VectorUtils.get_projection_value(p2, line_data[i]['azimuth'])
                    
                    if abs(v1 - v2) < tol_gps:
                        adj[i].append(j)
                        adj[j].append(i)

        # Identificar Passadas únicas (Unindo segmentos da Etapa 1)
        passadas_unidas = []
        visited = set()
        for i in range(len(line_data)):
            if i in visited or line_data[i]['type'] == 'CURVA': continue
            component = []
            queue = [i]
            visited.add(i)
            while queue:
                u = queue.pop(0)
                component.append(u)
                for v in adj[u]: 
                    if v not in visited: 
                        visited.add(v); queue.append(v)
            
            # Tirar média de azimute da passada unida
            pass_az = sum(line_data[idx]['azimuth'] for idx in component) / len(component)
            passadas_unidas.append({'indices': component, 'az': pass_az})

        # Dividir em GRUPOS (Blocos direcionais como Chapadão vs Bicos)
        grupos_direcionais = []
        visited_pass = set()
        for i, p1 in enumerate(passadas_unidas):
            if i in visited_pass: continue
            bloco = []
            queue = [i]
            visited_pass.add(i)
            while queue:
                u = queue.pop(0)
                bloco.append(u)
                for v, p2 in enumerate(passadas_unidas):
                    if v not in visited_pass:
                        az_diff = abs(passadas_unidas[u]['az'] - p2['az'])
                        if az_diff > 180: az_diff = 360 - az_diff
                        # Se azimute for próximo, pertence ao mesmo bloco direcional
                        if az_diff < desvio_tipo:
                            visited_pass.add(v); queue.append(v)
            grupos_direcionais.append(bloco)

        feedback.pushInfo(f"Total de Grupos (Blocos) detectados: {len(grupos_direcionais)}")

        # ETAPA 2 — NUMERAR AS LINHAS PARA CADA GRUPO
        for g_idx, bloco in enumerate(grupos_direcionais, 1):
            rows_to_sort = []
            
            # IMPORTANTE: Para ordenar sem embaralhar, precisamos de um azimute de referência único para o grupo
            grupo_az_ref = sum(passadas_unidas[p_idx]['az'] for p_idx in bloco) / len(bloco)
            
            feedback.pushInfo(f"Processando Grupo {g_idx}: {len(bloco)} passadas, Azimute Ref: {grupo_az_ref:.2f}°")

            for pass_idx in bloco:
                passada = passadas_unidas[pass_idx]
                
                # Valor médio de projeção da passada usando o azimute de referência do grupo
                proj_vals = []
                for idx in passada['indices']:
                    p = line_data[idx]['centroid']
                    # Fórmula solicitada: valor = -x * sin(azimute) + y * cos(azimute)
                    val = VectorUtils.get_projection_value(p, grupo_az_ref)
                    proj_vals.append(val)
                
                avg_proj = sum(proj_vals) / len(proj_vals)
                rows_to_sort.append({'pass_idx': pass_idx, 'proj': avg_proj})

            # Ordenar passadas do grupo pelo valor de projeção espacial
            rows_to_sort.sort(key=lambda x: x['proj'])
            
            for seq, row_info in enumerate(rows_to_sort, 1):
                for idx in passadas_unidas[row_info['pass_idx']]['indices']:
                    line_data[idx]['grupo_id'] = g_idx
                    line_data[idx]['seq_num'] = seq
                    feedback.pushInfo(f" -> Feição {line_data[idx]['fid']}: Grupo {g_idx}, Seq {seq} (Proj: {row_info['proj']:.2f})")

        # Salvar feições processadas no sink de saída
        for d in line_data:
            out_feat = QgsFeature(fields)
            out_feat.setGeometry(d['feat'].geometry())
            new_attrs = d['feat'].attributes()
            new_attrs.extend([d['grupo_id'], d['seq_num'], d['type'], d['azimuth']])
            out_feat.setAttributes(new_attrs)
            sink.addFeature(out_feat, QgsFeatureSink.FastInsert)

        return {self.OUTPUT: dest_id}